//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etkinlik_Takip_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlikler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Etkinlikler()
        {
            this.Incelemelers = new HashSet<Incelemeler>();
            this.Katilimlars = new HashSet<Katilimlar>();
            this.EtkinlikTurleris = new HashSet<EtkinlikTurleri>();
            this.Organizatorlers = new HashSet<Organizatorler>();
        }
    
        public int EtkinlikID { get; set; }
        public string Baslik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
        public string Yer { get; set; }
        public Nullable<int> KatilimciSayisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incelemeler> Incelemelers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Katilimlar> Katilimlars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtkinlikTurleri> EtkinlikTurleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organizatorler> Organizatorlers { get; set; }
    }
}
