//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etkinlik_Takip_Sistemi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incelemeler
    {
        public int IncelemeID { get; set; }
        public Nullable<int> EtkinlikID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public string Yorum { get; set; }
        public Nullable<int> Puan { get; set; }
    
        public virtual Etkinlikler Etkinlikler { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
    }
}
