//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Etkinlik_Takip_Sistemi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ActivityEntities : DbContext
    {
        public ActivityEntities()
            : base("name=ActivityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etkinlikler> Etkinliklers { get; set; }
        public virtual DbSet<EtkinlikTurleri> EtkinlikTurleris { get; set; }
        public virtual DbSet<Incelemeler> Incelemelers { get; set; }
        public virtual DbSet<Katilimlar> Katilimlars { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Organizatorler> Organizatorlers { get; set; }
    }
}
